### ISSUE TITLE
dictionary compression on values?

### ISSUE THREAD

**Issue by behrad** [dcodeIO/PSON#2]
It seems PSON only uses dictionary against json keys not the values, right? I want my String values to be compressed using a static dictionary. Can I achieve this or should I use LZ compressions against my string keys first ?

**Comment by dcodeIO** [comment]
If the string type value is in the dictionary, it should also be encoded as a reference:

https://github.com/dcodeIO/PSON/blob/master/src/PSON/Encoder.js#L103

**Comment by behrad** [comment]
thanks @dcodeIO Can you show me any example dict?
what I found in your code was a json array! not an Object :)

**Comment by dcodeIO** [comment]
The dictionary actually is an array, holding all the string values to replace by references. The value sent over the wire is the respective array index. The receiving side then needs to use the same dictionary and hence is able to look up the original string through it.

**Comment by behrad** [comment]
so if I have 

``` json
{
  "name": "some important text"
}
```

and I wanna add important to my dict, what should I write since `["important"]` didn't worked.
Should it be `[ {important:1} ]`

**Comment by dcodeIO** [comment]
Try:

``` js
var dict = ["name", "some important text"];
```

**Comment by behrad** [comment]
on no! I only know of some of the words in my value string which is dynamic, I could wrote something like:

``` js
va dict = [ "name", "important"]
```
