### ISSUE TITLE
Example of Streaming?

### ISSUE THREAD

**Issue by elidoran** [dcodeIO/PSON#7]
The example in the README shows decoding a buffer with the encoded bytes already nicely in a buffer all by itself.

I can stream a series of those buffers across the network to another process, but, how do I then separate those chunks again to provide them to PSON's `decode()` in exact chunks for decoding? 
How do we select the chunk of bytes we should pass to `decode()` ?

For example, sending JSON we could use a newline character, split on the newline character, and `JSON.parse()` the data between newlines.

Alternatively, if a decoder understood it is getting chunks of data at a time we could pass data chunks as we get them and it would return decoded objects only if there were any complete ones within the data. It would hold onto extra data waiting for the next chunk to hopefully provide enough to complete an object. Eventually, all data chunks are received and all objects are decoded.

How do we do this with PSON ?

```javascript
// for example, a receiving transform
// wants to decode and then push the objects for the next stream.
var decoder = new ProgressivePair([ /* strings */ ])
var decode = new Transform({
  readableObjectMode: true,
  transform: function (data, _, next) {
    // this `data` chunk is likely to have data for
    // multiple objects
    object = decoder.decode(data)
    this.push(object)
    next()
  }
})

// or something more like
transform: function(data, _, next) {
    objects = decoder.decode(data)
    if (objects && objects.length > 0) {
      // for-loop the array and push each one
    }
    next()
}
// in flush() we can verify we've used up all the data
```

I don't see anything in the documentation on how we are supposed to accomplish this. Perhaps there's a particular byte value the encoding uses to mark the end of an encoding and I can split incoming data on that value?

Thank you

**Comment by dcodeIO** [comment]
Just like with JSON, a streaming format is not defined and must be defined by the user.

For example you could prepend the chunk length [as a varint](https://github.com/dcodeIO/bytebuffer.js/wiki/API#bytebufferwritevarint32value-offset) using bytebuffer.js to each subsequent message. The current version of PSON is based on bytebuffer.js anyway. Likewise, when decoding, you'd read the length prior to decoding the respective chunk.

**Comment by elidoran** [comment]
Thank you. I see what to do.
